### ISSUE TITLE
Can't install dialect via npm due to funk version reference

### ISSUE THREAD

**Issue by superstructor** [masylum/dialect#1]
Upgrade funk to 0.0.2 in the package.json file. Currently dialect is not installable due to referring to 0.0.1:

```
npm install dialect
npm info it worked if it ends with ok
npm info using npm@0.2.5-1
npm ERR! Error installing funk@0.0.1
npm ERR! Error: version not found: 0.0.1 undefined: funk/0.0.1
npm ERR!     at IncomingMessage.<anonymous>      (/home/isaac/apps/node/lib/node/.npm/npm/0.2.5-1/package/lib/utils/registry/request.js:98:19)
npm ERR!     at IncomingMessage.emit (events.js:41:20)
npm ERR!     at HTTPParser.onMessageComplete (http.js:112:23)
npm ERR!     at Client.onData [as ondata] (http.js:889:27)
npm ERR!     at IOWatcher.callback (net.js:498:29)
npm ERR!     at node.js:634:9
npm ERR! Report this *entire* log at <http://github.com/isaacs/npm/issues>
npm ERR! or email it to <npm-@googlegroups.com>
npm ERR! Just tweeting a tiny part of the error will not be helpful.
npm not ok
```

**Comment by masylum** [comment]
closed by 874627c25cff31f0c084f17dbb5e48c668660d5d

**Comment by masylum** [comment]
Try now, the package.json was a little bit outdated. Thanks for the feedback!

**Comment by superstructor** [comment]
Thanks for the quick fix and awesome module! 

I still get the same error. Did you publish it with npm publish ?

**Comment by masylum** [comment]
That's weird...
Try to: 
    npm update funk

I just installed dialect on a fresh and clean machine and it installed all the packages correctly.

```
npm ls installed

dialect@0.0.4   =masylum active installed latest remote
eyes@0.1.6      =cloudhead active installed latest stable remote
funk@0.0.2      =masylum active installed latest remote
lingo@0.0.3     =tjholowaychuk active installed latest remote
mongodb@0.7.9   =christkv active installed latest stable remote
npm@0.2.5-1     =isaacs active installed latest remote
vows@0.5.2      =cloudhead active installed latest stable remote
```

**Comment by superstructor** [comment]
Thanks for your fix and help.

Finally I found I had to clear the cache for dialect :

<pre>npm cache clean dialect</pre>


After that installation worked as expected =)
